spring:
  application:
    name: gamification-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/gamification_db
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: gamification-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

server:
  port: 1111

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka