version: '3.8'
services:
  postgres:
    image: postgres:13.2
    environment:
      POSTGRES_DB: community_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
